version: "3"
services: 
  mongo:
    container_name: mongo-container
    image: mongo:5.0.6-focal
    restart: always
    volumes: 
      - /data:/data/db
    ports:
      - "27017:27017"

    api: 
      container_name: api-container
      build: .
      image: clean-node-api
      restart: always
      command: ["yarn", "start"]
      volumes: 
        - ./dist:/usr/src/clean-node-api/dist
      ports:
        - "5050:5050"
      links:
        - mongo
      environment: 
       - MONGO_URL=mongodb://mongo:27017/clean-node-api
       - JWT_SECRET=secret
      