
version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:17-alpine
    working_dir: /usr/src/clean-node-api
    restart: always
    command: sh -c "yarn install --only=prod && yarn run debug"
    volumes:
      - ./dist/:/usr/src/clean-node-api/dist/
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
    environment: 
       - MONGO_URL=mongodb://mongo:27017/clean-node-api
       - JWT_SECRET=secret
       - PORT= 5050